### ISSUE TITLE
Create 503 page 

### ISSUE THREAD

**Issue by tier3guy** [tier3guy/Acadmica#28]
create one 503 page - 503 page is the page displayed to the user when the server fails to respond. Take some inspiration from the internet.

**Comment by Aspireve** [comment]
Hey @tier3guy Could I try to do it?

**Comment by tier3guy** [comment]
Go for it.

**Comment by Aspireve** [comment]
Hey I just realized you have a 404 error page but for some reason it isnt showing on the main site
it shows this instead

**Comment by Aspireve** [comment]
I thought I could find out how its made so that I could get inspiration for the 503 page

**Comment by Aspireve** [comment]
You might have to folow the [Creating a custom 404 page for your GitHub Pages site](https://docs.github.com/en/pages/getting-started-with-github-pages/creating-a-custom-404-page-for-your-github-pages-site) to make the 404 page more accessible and similarly for the 503 page. Ill create the 503 HTML and CSS page and push it soon

**Comment by Aspireve** [comment]
So I came up with this page. It is made with the same stylesheet as the 404 error page so that the design looks consistent throughout the document
![image](https://user-images.githubusercontent.com/93852415/179467061-6d34741a-cfcb-43df-8c13-91d1f0f25457.png)
And on pressing the Refresh button it redirects you to the index.html page, which if the site isnt up yet will again issue a 503 error page and would send the user back to the 503.html page
![503 Server Error - Google Chrome 2022-07-18 13-21-02](https://user-images.githubusercontent.com/93852415/179467688-be99e2ec-6592-4fd2-9807-b5216d5fb19b.gif)

**Comment by tier3guy** [comment]
@Aspireve the design of the 4O4 has been updated, take the inspiration from it and please try re-design it. We want a minimal design.

**Comment by Aspireve** [comment]
Oh sure Ill make it soon and Push it

**Comment by Aspireve** [comment]
@tier3guy The new 404 page looks awesome!!

How's this?
![image](https://user-images.githubusercontent.com/93852415/179488286-4787b3a6-0eee-4411-87d1-aa9324fa6213.png)

**Comment by tier3guy** [comment]
You are good to go with it.

**Comment by tier3guy** [comment]
Push the changes.

**Comment by Aspireve** [comment]
Yup Ill push it soon!!
